### PR TITLE
updates jquery

### PR DESCRIPTION
**Pull request by ghost**
Not entirely sure I did everything correctly - these were my steps:
1. Deleted package-lock.json and node_modules
2. In bower.json I changed jquery to 3.6.0
3. Changed the Texas search API from v2.0 to v2.1
4. Ran `npm install jquery`, `npm install`, `bower install`. package.json now has jquery listed at the latest version: ^3.6.0
5. Ran locally and clicked around to see if everything worked/see if any console errors appeared
6. Once this gets merged, I'll build and deploy on S3

The issue stated: "Acunetix scan reports this app is using jQuery 2.2.4 (fonts) and 3.4.1 (main site) and should be updated. This is a Medium vulnerability and should be a priority."
I didn't see a separate definition for jQuery fonts anywhere, and I hope that updating. reinstalling the overall jQuery fixed that. If you think I'm missing something, let me know!

### CODE REVIEW

**Review by BlakeDraper — APPROVED** [review]
These changes all look fine.

**Comment by BlakeDraper** [comment]
@09Kathy don't forget to do a dist build with `gulp build` for this PR so that it is ready to deploy. You can just do that on this branch and commit/push.

**Comment by 09Kathy** [comment]
pretty sure that build files don't get push up to github (maybe for security reasons? I'm not sure). At any rate, I have it locally

**Comment by BlakeDraper** [comment]
Hm - I'm not aware of a security issue with that. The build folder is not in the gitignore of this rep, so we always have committed the build in the past. It's fairly common to update a server with latest build/dist using git clone or git pull which requires that build stuff to be in the remote repo.  I know that is not how we update this particular app though.

**Pull request merged**
